version: '3'
services:
  app:
    build:
      context: .
    tty: true
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"